Send message
rodrieiz/rails-api-learning-camp pull request #10
Opened 2021-08-28 16:33 UTC by rodrieiz

https://trello.com/c/WQbErDPV/29-5-as-a-user-i-should-be-able-to-send-a-message-in-a-conversation-with-any-of-my-compatible-targets-so-i-can-talk-about-our-commo

2021-08-30 13:49 UTC, enzofab91 reviewed
I'm a bit confuse, I think it has some files that are not related to the feature, isn't it?

Furthermore, to create a chat you can use [Action Cable](https://guides.rubyonrails.org/action_cable_overview.html)

2021-08-30 13:49 UTC, enzofab91 commented on app/controllers/messages_controller.rb
> +    if @conversation && (current_user == @conversation.user1 || current_user == @conversation.user2)
The `current_user` is both `user1` and `user2` 🤔

2021-08-30 14:05 UTC, DJA89 commented on app/controllers/messages_controller.rb
> +    @conversation = Conversation.find(message_params[:conversation_id])
If conversations belong to users, I think this could also work if you want to do it shorter:
`@conversation = current_user.conversations.find(message_params[:conversation_id])`

2021-08-30 14:07 UTC, DJA89 requested changes

2021-08-30 14:07 UTC, DJA89 commented on app/controllers/targets_controller.rb
> +      @matches = FindMatch.new(@target, current_user).search
This should probably go in an `after_create` on the model itself.

2021-08-30 14:07 UTC, DJA89 commented on app/models/conversation.rb
> +  def user1_distint_of_user2
distinct*

2021-08-31 12:16 UTC, rodrieiz commented on app/controllers/messages_controller.rb
> +    if @conversation && (current_user == @conversation.user1 || current_user == @conversation.user2)
Nop, the current_user can be user1 OR user2 in the conversation

2021-09-01 01:09 UTC, rodrieiz commented on app/controllers/messages_controller.rb
> +    @conversation = Conversation.find(message_params[:conversation_id])
I tried but it didn't work

2021-09-02 20:09 UTC, enzofab91 reviewed
Good work! Left some comments.

2021-09-02 20:09 UTC, enzofab91 commented on app/channels/application_cable/conversation_channel.rb
> +      stream_from "conversations_#{conversation.id}"
```suggestion
      stream_for "conversations_#{conversation.id}"
```

I think [stream_from](external_repositories) is for broadcasting.

2021-09-02 20:09 UTC, enzofab91 commented on spec/channels/conversation_channel_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Add some test here. Can be helpful https://guides.rubyonrails.org/testing.html#testing-action-cable and https://github.com/palkan/action-cable-testing

2021-09-02 20:09 UTC, enzofab91 commented on app/services/message_relay_job.rb
> +class MessageRelayJob < ApplicationJob
Would be nice to do this in channel.

2021-09-02 20:09 UTC, enzofab91 commented on app/channels/application_cable/conversation_channel.rb
> +      if msg.save
```suggestion
      Message.create!(
        conversation_id: @conversation.id,
        user_id: current_user.id,
        message: data['message'].present? ? data.fetch('message') : nil
      )
```

2021-09-02 22:59 UTC, rodrieiz commented on app/channels/application_cable/conversation_channel.rb
> +      stream_from "conversations_#{conversation.id}"
Fixed

2021-09-03 13:24 UTC, enzofab91 approved these changes
Good work 👏

2021-09-03 14:44 UTC, DJA89 approved these changes

2021-09-06 11:42 UTC, merged